// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOAD.Data;

#nullable disable

namespace OOAD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260505114034_RemoveReminderMessage")]
    partial class RemoveReminderMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CalendarId");

                    b.ToTable("Appointments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Appointments");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CalendarId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            CalendarId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CalendarId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            CalendarId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            CalendarId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CalendarId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("OOAD.Model.Reminders", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupMeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReminderId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId", "GroupMeetingId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("OOAD.Model.UserGroupMeetings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupMeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GroupMeetingId");

                    b.HasIndex("GroupMeetingId");

                    b.ToTable("UserGroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "nnguyenlinh33662222@gmail.com",
                            FullName = "Nguyễn Đỗ Khánh Linh",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            PhoneNumber = "0900000001"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "ntctuyen06@gmail.com",
                            FullName = "Nguyễn Thị Cẩm Tuyền",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            PhoneNumber = "0900000002"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "dieuhoale6406@gmail.com",
                            FullName = "Lê Thị Diệu Hòa",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            PhoneNumber = "0900000003"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "vanngocnhuy30032006@gmail.com",
                            FullName = "Văn Ngọc Như Ý",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            PhoneNumber = "0900000004"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "nguyenvanan@gmail.com",
                            FullName = "Nguyễn Văn An",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            PhoneNumber = "0900000005"
                        });
                });

            modelBuilder.Entity("OOAD.Model.GroupMeetings", b =>
                {
                    b.HasBaseType("OOAD.Model.Appointments");

                    b.HasDiscriminator().HasValue("GroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.HasOne("OOAD.Model.Calendars", "Calendar")
                        .WithMany("Appointments")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.HasOne("OOAD.Model.Users", "User")
                        .WithOne("Calendar")
                        .HasForeignKey("OOAD.Model.Calendars", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OOAD.Model.Reminders", b =>
                {
                    b.HasOne("OOAD.Model.Appointments", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OOAD.Model.UserGroupMeetings", "UserGroupMeeting")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId", "GroupMeetingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");

                    b.Navigation("UserGroupMeeting");
                });

            modelBuilder.Entity("OOAD.Model.UserGroupMeetings", b =>
                {
                    b.HasOne("OOAD.Model.GroupMeetings", "GroupMeeting")
                        .WithMany("UserGroupMeetings")
                        .HasForeignKey("GroupMeetingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OOAD.Model.Users", "User")
                        .WithMany("UserGroupMeetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupMeeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("OOAD.Model.UserGroupMeetings", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("OOAD.Model.Users", b =>
                {
                    b.Navigation("Calendar")
                        .IsRequired();

                    b.Navigation("UserGroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.GroupMeetings", b =>
                {
                    b.Navigation("UserGroupMeetings");
                });
#pragma warning restore 612, 618
        }
    }
}
