// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOAD.Data;

#nullable disable

namespace OOAD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CalendarId");

                    b.ToTable("Appointments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Appointments");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CalendarId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("OOAD.Model.Reminders", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReminderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("OOAD.Model.UserGroupMeetings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupMeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GroupMeetingId");

                    b.HasIndex("GroupMeetingId");

                    b.ToTable("UserGroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OOAD.Model.GroupMeetings", b =>
                {
                    b.HasBaseType("OOAD.Model.Appointments");

                    b.HasDiscriminator().HasValue("GroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.HasOne("OOAD.Model.Calendars", "Calendar")
                        .WithMany("Appointments")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.HasOne("OOAD.Model.Users", "User")
                        .WithOne("Calendar")
                        .HasForeignKey("OOAD.Model.Calendars", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OOAD.Model.Reminders", b =>
                {
                    b.HasOne("OOAD.Model.Appointments", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("OOAD.Model.UserGroupMeetings", b =>
                {
                    b.HasOne("OOAD.Model.GroupMeetings", "GroupMeeting")
                        .WithMany("UserGroupMeetings")
                        .HasForeignKey("GroupMeetingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OOAD.Model.Users", "User")
                        .WithMany("UserGroupMeetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupMeeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OOAD.Model.Appointments", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("OOAD.Model.Calendars", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("OOAD.Model.Users", b =>
                {
                    b.Navigation("Calendar")
                        .IsRequired();

                    b.Navigation("UserGroupMeetings");
                });

            modelBuilder.Entity("OOAD.Model.GroupMeetings", b =>
                {
                    b.Navigation("UserGroupMeetings");
                });
#pragma warning restore 612, 618
        }
    }
}
